/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";

export namespace Components {
    interface AppAuth {}
    interface AppHome {
        quote: QuoteState;
    }
    interface AppList {}
    interface AppProfile {}
    interface AppQuote {
        quote: QuoteState;
    }
    interface AppRoot {}
}

declare global {
    interface HTMLAppAuthElement extends Components.AppAuth, HTMLStencilElement {}
    var HTMLAppAuthElement: {
        prototype: HTMLAppAuthElement;
        new (): HTMLAppAuthElement;
    };

    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };

    interface HTMLAppListElement extends Components.AppList, HTMLStencilElement {}
    var HTMLAppListElement: {
        prototype: HTMLAppListElement;
        new (): HTMLAppListElement;
    };

    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };

    interface HTMLAppQuoteElement extends Components.AppQuote, HTMLStencilElement {}
    var HTMLAppQuoteElement: {
        prototype: HTMLAppQuoteElement;
        new (): HTMLAppQuoteElement;
    };

    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-auth": HTMLAppAuthElement;
        "app-home": HTMLAppHomeElement;
        "app-list": HTMLAppListElement;
        "app-profile": HTMLAppProfileElement;
        "app-quote": HTMLAppQuoteElement;
        "app-root": HTMLAppRootElement;
    }
}

declare namespace LocalJSX {
    interface AppAuth {}
    interface AppHome {
        quote?: QuoteState;
    }
    interface AppList {}
    interface AppProfile {}
    interface AppQuote {
        quote?: QuoteState;
    }
    interface AppRoot {}

    interface IntrinsicElements {
        "app-auth": AppAuth;
        "app-home": AppHome;
        "app-list": AppList;
        "app-profile": AppProfile;
        "app-quote": AppQuote;
        "app-root": AppRoot;
    }
}

export { LocalJSX as JSX };

declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-auth": LocalJSX.AppAuth & JSXBase.HTMLAttributes<HTMLAppAuthElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-list": LocalJSX.AppList & JSXBase.HTMLAttributes<HTMLAppListElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-quote": LocalJSX.AppQuote & JSXBase.HTMLAttributes<HTMLAppQuoteElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
